### ISSUE TITLE
Debug info?

### ISSUE THREAD

**Issue by AfterSpencer** [sensu/sensu-email-handler#11]
I have setup the handler, but I am not certain it is doing anything. Is there a way to get debug info assuming it is firing or is is logging somewhere?

**Comment by nixwiz** [comment]
@AfterSpencer have you tried running it from the command line using a sample event JSON? There's one in this repository you can use.  If something is failing, it should report as such.

**Comment by AfterSpencer** [comment]
I am not 100% clear what you mean. I used the sample JSON to create the handler:

`cat go_mailer.json
{
    "api_version": "core/v2",
    "type": "Handler",
    "metadata": {
        "namespace": "default",
        "name": "email"
    },
    "spec": {
        "type": "pipe",
        "command": "/var/lib/sensu/sensu-agent/sensu-email-handler -P 465 -f <redacted>@gmail.com -t <redacted>@gmail.com -s smtp.googlemail.com -u <redacted>@gmail.com -p '<redacted>'",
        "timeout": 10,
        "filters": [
            "is_incident",
            "not_silenced"
        ]
    }
}
`

Which looks like this when I look at sensuctl:

`sensuctl handler list
  Name    Type   Timeout           Filters            Mutator                                                                                                 Execute                                                                                                  Environment Variables   Assets
 ─────── ────── ───────── ────────────────────────── ───────── ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ─────────────────────── ────────
  email   pipe        10   is_incident,not_silenced             RUN:  /var/lib/sensu/sensu-agent/sensu-email-handler -P 465 -f <redacted>@gmail.com -t <redacted>@gmail.com -s smtp.googlemail.com -u <redacted>@gmail.com -p '<redacted>'`

I have it attached to all the checks as shown in sensctl:

`sensuctl check list
        Name                                                          Command                                                    Interval   Cron   Timeout   TTL   Subscriptions   Handlers   Assets   Hooks   Publish?   Stdin?   Metric Format   Metric Handlers
 ─────────────────── ────────────────────────────────────────────────────────────────────────────────────────────────────────── ────────── ────── ───────── ───── ─────────────── ────────── ──────── ─────── ────────── ──────── ─────────────── ─────────────────
  apache-status       /opt/sensu/embedded/bin/check-process.rb                                                                         60                0     0   linux           email                       true       false
  apt-status          /usr/lib/nagios/plugins/check_apt                                                                                60                0     0   linux           email                       true       false
  check-cpu           /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-cpu-checks-3.0.0/bin/check-cpu.sh -w 75 -c 90         60                0     0   linux           email                       true       false
  disk-status         sudo /opt/sensu/embedded/bin/check-disk-usage.rb -w 80 -c 90                                                     60                0     0   linux           email                       true       false
  local-load-status   /usr/lib/nagios/plugins/check_load -w 5.0,4.0,3.0 -c 10.0,6.0,4.0                                                60                0     0   linux           email                       true       false
  local-users         /usr/lib/nagios/plugins/check_users -w 5 -c 10                                                                   60                0     0   linux           email                       true       false
  procs-status        /usr/lib/nagios/plugins/check_procs -w 250 -c 400 -s RSZDT                                                       60                0     0   linux           email                       true       false
  swap-status         /usr/lib/nagios/plugins/check_swap -w 20 -c 10                                                                   60                0     0   linux           email                       true       false
`

When I run the command listed under the handler it seems to just hang without doing anything.

Thanks for responding! So far I like what I am seeing with Sensu Go.

**Comment by nixwiz** [comment]
Sorry for not being specific.  But there is a [sample event json file](https://github.com/sensu/sensu-email-handler/blob/master/event.json) in the repository.  Try using that to run the handler.

`cat event.json | /var/lib/sensu/sensu-agent/sensu-email-handler -P 465 -f <redacted>@gmail.com -t <redacted>@gmail.com -s smtp.googlemail.com -u <redacted>@gmail.com -p '<redacted>'
`

This should let you see any errors generated by the handler.

**Comment by AfterSpencer** [comment]
Gotcha! That is helpful. Here is the output

`cat ./event.json | /var/lib/sensu/sensu-agent/sensu-email-handler -P 465 -f <red>@gmail.com -t <red>@gmail.com -s smtp.googlemail.com -u <red>@gmail.com -p '<red>'
Error: failed to send email: EOF
Usage:
  sensu-email-handler [flags]

Flags:
  -f, --fromEmail string      The 'from' email address
  -h, --help                  help for sensu-email-handler
  -s, --smtpHost string       The SMTP host to use to send to send email
  -p, --smtpPassword string   The SMTP password
  -P, --smtpPort uint16       The SMTP server port (default 587)
  -u, --smtpUsername string   The SMTP username
  -t, --toEmail string        The 'to' email address

`

**Comment by nixwiz** [comment]
Can you try changing the port to 587 and see if that changes anything?

**Comment by AfterSpencer** [comment]
That was it! I was using 465 because that is what some of my other config uses and it works. Thanks for the help!

**Comment by nixwiz** [comment]
My pleasure, glad that fixed it for you.

**Comment by fanpero87** [comment]
Hello,
I have a similar problem. I want to test the email handler with my own SMTP server running on port 25 and that doesn't require any username or password.

From the external server that runs sensuctl I did this:
```
sensuctl event info webserver keepalive --format=json | \
  sensu-email-handler -f sensu@domain.com \
  -t monitor@domain.com -s relay.domain.com \
  -P 25 -S 'testing'
```
If I try that, I got:
``` 
sensu-email-handler: command not found
Error: not found
```

How can I test my email handler to make it work with my SMTP server?
