### ISSUE TITLE
Support a template file for email body

### ISSUE THREAD

**Issue by jaredledvina** [sensu/sensu-email-handler#14]
One very useful feature I've see is that https://github.com/sensu-plugins/sensu-plugins-mailer supports parsing an ERB template for the email body. Reviewing this handler, it appears that the body is mostly hardcoded to the check definition. 

I think a major improvement would be to support passing in a file that can be used as a template for the body itself. I'd be willing to spend some free time on the side to put something together for this feature. 

Does the Sensu team have thoughts on a preferred templating solution? If I remember correctly, Go templates didn't work perfectly for the Sensu Go filters and it's now javascript based? 

Lemme know if you think this is a worthwhile feature!

**Comment by nixwiz** [comment]
It already makes use of Go templates/token substitution in the body [here](https://github.com/sensu/sensu-email-handler/blob/42f9b9caae728be66736ae35e01dbe3dbc5de7a0/main.go#L109) to optionally include the output from any check hooks.

It should be relatively easy to add an argument with a path to a file containing similar templating and stuffing that into the message body template to be resolved.
