### ISSUE TITLE
Error: failed to send email: 504 5.7.4 Unrecognized authentication type 

### ISSUE THREAD

**Issue by cimere** [sensu/sensu-email-handler#18]
Hi,
I'm trying to send emails using `smtp.office365.com` but I get this error:

`Error: failed to send email: 504 5.7.4 Unrecognized authentication type [DBBPR09CA0015.eurprd09.prod.outlook.com]`

I'm using the same credential/settings successfully used by other applications (e.g. grafana).

Thanks

**Comment by cimere** [comment]
It seems that outlook 365 doesn’t support PLAINTEXT or CRAMMD5 Auth.

**Comment by nixwiz** [comment]
@cimere I may have a fix, but I have no way of testing.  If I were to provide you a binary, could you test it?  If so, what OS/arch (Linux amd64)?

**Comment by cimere** [comment]
@nixwiz thank you, I compiled your branch but It didn't work (same error). 
I managed to fix it somehow using some old x/net library I found on another project (https://github.com/farmerx/mail). You can find my branch at https://github.com/cimere/sensu-email-handler. It isn't polished at all but it could be used as a starting point to fix the problem.

**Comment by cimere** [comment]
@nixwiz it worked! than you.

**Comment by nixwiz** [comment]
@cimere so it worked with the -l (--loginauth) option I added?  I saw you commented prior that it didn't.

**Comment by cimere** [comment]
@nixwiz yes, it worked with the -l option. I deleted the previous comment because it didn't work but it was my fault.
