### ISSUE TITLE
Is it able to parse a html or erb templates?

### ISSUE THREAD

**Issue by balajik1992** [sensu/sensu-email-handler#20]
Hi Team,

I have template as mentioned below
Sensu Alert - {{.Entity.Name}}

I am able to parse above template and I have received email

Is this script able to parse html or erb template as mentioned below
<html>
<head>
</style>
</head>
<body>
        <tr >
                <td>Check Name: </td>
                <td> {{.Check.Name}}
                </td>
        </tr>
</body>
</html>

As I checked, I am not able to parse it 
How Can I present the mail in a tabular format

**Comment by nixwiz** [comment]
Parse html or erb?  No, it's just uses Go templating to access the event (entity and check) details.  But you should be able to embed HTML within the template.  Something like this simple example would work*:

`"<html><body><table><tr><td>Entity</td><td>{{.Entity.Name}}</td></tr><tr><td>Check</td><td>{{.Check.Name}}</td></tr><tr><td>State</td><td>{{.Check.State}}</td></tr></table></body></html>"`

*That is assuming the `Content-Type: text/html header` is included in the message.  I have a [pull request](https://github.com/sensu/sensu-email-handler/pull/17) pending that adds in annotation support (as well as allowing.  I've also added to it checking the body for the `<html>` tag and setting the message's Content-Type header.  That should help with this.
