### ISSUE TITLE
Is it possible to send to multiple recipients?

### ISSUE THREAD

**Issue by mildgrim** [sensu/sensu-email-handler#22]
Hi,

I'm having trouble figuring out how to send alerts to more than one recipient. Would I need multiple handlers or can I somehow pass in more than one email address?

Looking at https://golang.org/pkg/net/smtp/#pkg-examples the underlying code seems to take a string array but the variable in this handler asset seems to only handle string and I can't quite figure out if it supports multiple recipients or not. I've tried a lot of different types of syntaxes with no luck.

//Sebastian Mildgrim

**Comment by tenzone** [comment]
i have been using a main handler set called `mailer` and a separate handler for each contact. then use the `sensu-go-contact-filter` (find it on bonsai) and add a label to each check to define the contacts for each check.

**Comment by mildgrim** [comment]
That's pretty brilliant, thanks! I'll go ahead and close this then, seeing as that workaround should fill my need adequately.
