### ISSUE TITLE
Anonymous mail with STARTTLS not supported by insecure flag

### ISSUE THREAD

**Issue by bluekeyes** [sensu/sensu-email-handler#24]
The `--insecure` flag currently combines several settings that are valid independently into a single option:

- It forces the port to 25
- It disables `STARTTLS` handling (with the intent of ignoring invalid TLS certificates)
- It disables authentication

In my case, our internal mail server allows anonymous access, but requires TLS (and uses valid certificates). With the current code, using the `--insecure` flag causes this error:

```
error executing handler: EOF
```

I believe this is because the server closes the connection on port 25 when `StartTLS` is not called. Using `smtp.SendMail(...)` with a `nil` auth implementation works as expected (tested with a local build of the handler.)

I propose the following changes:

- Remove the `--insecure` flag
- Add a new `--tls-skip-verify` flag to disable TLS certificate checks while still supporting TLS connections.
- Add a new `--auth-method` flag that can take values `none`, `plain`, or `login` with a default value of `plain`. This would also remove the `enableLoginAuth` flag. As an alternative, a new `--anonymous` flag could be added to disable the username/password check.
- Require users to provide the existing `--smptPort` flag to use a non-default port

I've started implementing this, but wanted to file an issue for discussion as well since it involves breaking the current interface.

**Comment by nixwiz** [comment]
Given its breaking nature, might I suggest not completely removing `--insecure`, but maybe deprecate it by having it print an error (and maybe suggesting the appropriate new flag combinations?) and exiting?  The --help/usage could do so as well.
