### ISSUE TITLE
Feature Request: additional template functions

### ISSUE THREAD

**Issue by hurrycaine** [sensu/sensu-email-handler#45]
In Golang there are minimal built in functions to manipulate values (being resolved in the template). For more complex things you can create your own custom template functions or methods attached to the data you execute. Even common string manipulations are not in the built in functions.

I have an example where I need to split the entity name on a hyphen to get an abbreviated name for the subject line.  I could write a custom split function to add to handler but after a quick search there is a robust package called sprig. Probably more then we need and if anything is missing then the new function could be added to sprig.

[github](https://github.com/Masterminds/sprig)
[func docs](https://masterminds.github.io/sprig/)
[godoc](https://godoc.org/github.com/Masterminds/sprig)

If sounds good, I can put in a PR.

**Comment by hurrycaine** [comment]
I sent a PR with sprig added and some examples that I am personally using.  I think sprig is a little over kill but should add a lot of flexibility to our templates now.  This should bring into parity what we had with the ruby templates.

Otherwise we would need to start to add functions in ones and twos.

**Comment by jspaleta** [comment]
Wow thanks!
This looks great.
I think we can get this merged and updated real quick

**Comment by jspaleta** [comment]
In fact... sprig might be something we add to the sensu go plugin sdk so it can benefit all the handlers that need this functionality.  I think I'll merge it here.. but look into refactoring this as part of sdk functionality

**Comment by jspaleta** [comment]
@hurrycaine 
If you haven't yet...
Register your PR here: https://sensu.io/register-your-contribution
so we can send you some thank you swag

**Comment by jspaleta** [comment]
merged and now in 1.2 release
