### ISSUE TITLE
set the version information in the builds

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-email-handler#65]
Looks like we aren't setting the version information.

Just downloaded the 0.9.0 release tarball 
```
./sensu-email-handler version
dev, commit none, built at unknown
```

**Comment by nixwiz** [comment]
The code for this in goreleaser is already in place from the maintenance PR (#64).

[Reference](https://github.com/sensu/sensu-email-handler/blame/d4d8fdca0d31e2a03f9c835f9189dfd7f2eef2ab/.goreleaser.yml#L7)
