### ISSUE TITLE
sensu-email-handler not working with postfix 3.3.0

### ISSUE THREAD

**Issue by schampseix** [sensu/sensu-email-handler#7]
## Expected Behavior
Be able to use sensu-email-handler with postfix relay in version 3.3.0

## Current Behavior
The handler isn't compliant with postfix 3.3.0 which implemente new feature on Header "From" : 
http://www.postfix.org/announcements/postfix-3.3.0.html

when sensu send an email to our postfix relay smtp in version 3.3.0 this one is returning : 
Feb  1 16:03:21 tech-smtp postfix/qmgr[25813]: 3917BBC446: from=<sensu@XXXXX>, size=410, nrcpt=1 (queue active)
Feb  1 16:03:21 tech-smtp postfix/smtpd[9968]: disconnect from ip-XX.XX.XX.XX[X.X.X.X] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Feb  1 16:03:21 tech-smtp postfix/relay/smtp[9965]: Untrusted TLS connection established to aspmx.l.google.com[74.125.193.27]:25: TLSv1.2 with cipher ECDHE-RSA-CHACHA20-POLY1305 (256/256 bits)
Feb  1 16:03:21 tech-smtp postfix/relay/smtp[9965]: 3917BBC446: to=<My_EMAIL@XXXXX>, relay=aspmx.l.google.com[74.125.193.27]:25, delay=0.39, delays=0.01/0/0.14/0.24, dsn=5.7.1, status=bounced (host aspmx.l.google.com[74.125.193.27] said: 550-5.7.1 [X.X.X.X      11] Our system has detected that this message is 550-5.7.1 not RFC 5322 compliant: 550-5.7.1 'From' header is missing. 550-5.7.1 To reduce the amount of spam sent to Gmail, this message has been 550-5.7.1 blocked. Please visit 550-5.7.1  https://support.google.com/mail/?p=RfcMessageNonCompliant 550 5.7.1 and review RFC 5322 specifications for more information. r9-v6si3788066ejp.209 - gsmtp (in reply to end of DATA command))

## Possible Solution or workaround 
Use postfix version 3.1.0 which is working with sensu handler : 
Feb  1 14:46:19 imail-prod postfix/smtpd[16000]: connect from unknown[X.X.X.X]
Feb  1 14:46:19 imail-prod postfix/smtpd[16000]: 2308B23E00: client=unknown[X.X.X.X]
Feb  1 14:46:19 imail-prod postfix/cleanup[16795]: 2308B23E00: message-id=<>
Feb  1 14:46:19 imail-prod postfix/qmgr[385]: 2308B23E00: from=<sensu@XXXXXXX>, size=368, nrcpt=1 (queue active)
Feb  1 14:46:19 imail-prod postfix/smtpd[16000]: disconnect from unknown[X.X.X.X] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Feb  1 14:46:19 imail-prod postfix/smtp[16801]: Untrusted TLS connection established to aspmx.l.google.com[64.233.167.26]:25: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Feb  1 14:46:19imail-prod postfix/smtp[16801]: 2308B23E00: to=<MY_MAIL@XXXXX>, relay=aspmx.l.google.com[64.233.167.26]:25, delay=0.34, delays=0.05/0/0.09/0.2, dsn=2.0.0, status=sent (250 2.0.0 OK 1549028779 n17si436556wro.438 - gsmtp)
Feb  1 14:46:19 imail-prod postfix/qmgr[385]: 2308B23E00: removed

## Steps to Reproduce (for bugs)
execute email handler through a smtp server postfix 3.3.0

## Your Environment
Backend which exec the handler are in v5.1.1 under ubuntu 18.04

**Comment by echlebek** [comment]
@schampseix would you mind testing the PR that @nixwiz submitted?
